### ISSUE TITLE
Conflict with Media & Text Block

### ISSUE THREAD

**Issue by turtlepod** [bu-ist/bu-blocks#291]
@ashleykolodziej, @smy315 found a bug (conflict with wp core media & text block) when working on BU Blocks

screenshot:
![967667cba33b5f9f8be820cb432ed609](https://user-images.githubusercontent.com/1705549/99254317-c3a21a80-2844-11eb-8673-90f7af342023.png)

You can check the issue here:
https://id-editorial.cms-devl.bu.edu/wp-admin/post.php?post=249660&action=edit

Here's the video of  the issue:
https://drive.google.com/file/d/1IFtJsDJcjVIvi9l-kjrycEwR8U-07Gl9/view?usp=sharing

Thank you

**Comment by acketon** [comment]
I think I've identified the issue in this line of code: https://github.com/bu-ist/bu-blocks/blob/develop/src/blocks/clicktotweet/clicktotweet.js#L199

@philcable's code is checking for clicktotweet format off & content empty on a paragraph block. This is causing this code to run repeatedly on empty paragraph blocks. Both inside the Media & Text block and even in the default block inserter.

**Comment by acketon** [comment]
This looks like a bug with that line of code in WP 5.4. I didn't see this behavior in WP 4.9. Similar to some of the other bugs we had to fix and code we had to refactor that was originally written and fine in 4.9. I've found in 5.x that same code runs more frequently and leads to crashes or bugs. 

I don't know enough about React to know what changes upstream that causes this but it always seems to be errors related to calling setAttribute() type functions too often because they are being called in places that (total guess) they shouldn't be?

I'll add this to our list of bugs to look into. In the meantime @turtlepod it seems that deleting and re-adding that nested paragraph block fixes the issue in my test.

**Comment by turtlepod** [comment]
@acketon Thanks. and sometimes saving the post and refresh also works.
we'll use the work-around (remove + re-adding / save + refresh) to make this work.

Thanks for identifying the issue.
I created a fix here https://github.com/bu-ist/bu-blocks/pull/292
But, please test and review before merging to make sure all functionality working as expected.
